### ISSUE TITLE
Skidded name

### ISSUE THREAD

**Issue by Tecnio** [jasonlaubb/Matrix-AntiCheat#6]
The name is taken by Matrix AntiCheat which has been taken for YEARS.
https://matrix.rip/
https://builtbybit.com/resources/matrix-anticheat.13999/

**Comment by jasonlaubb** [comment]
We know

**Comment by jasonlaubb** [comment]
But it's a java AntiCheat, so I am no gonna change name

**Comment by jasonlaubb** [comment]
Issue ended
